name: First Workflow
on: workflow-dispatch
jobs:
  first-job: 
    runs-on: macos-15
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  
